#pragma once
// SPDX-License-Identifier: BSD-2-Clause

/* Public interface versions frozen for the 0.2.x developer-preview line. */
#define FBR34KER_PUBLIC_ABI_EPOCH 1U
#define FBR34KER_FBDP_PROTOCOL_VERSION 1U
#define FBR34KER_HANDOFF_ABI_VERSION 4U
#define FBR34KER_MODULE_ABI_VERSION 3U
#define FBR34KER_MODULE_FORMAT_ABI_VERSION 1U
#define FBR34KER_FMBC_BYTECODE_VERSION 2U
#define FBR34KER_BOARD_DESCRIPTION_ABI_VERSION 1U
#define FBR34KER_SERVICE_REGISTRY_ABI_VERSION 1U
#define FBR34KER_DRIVER_MANAGER_ABI_VERSION 1U
#define FBR34KER_BOOT_EVIDENCE_ABI_VERSION 1U
#define FBR34KER_RELEASE_MANIFEST_SCHEMA_VERSION 2U
#define FBR34KER_BOOT_IMAGE_ABI_VERSION 1U
#define FBR34KER_RECOVERY_PROFILE_SCHEMA_VERSION 1U
#define FBR34KER_FIRST_STAGE_ADAPTER_ABI_VERSION 1U
#define FBR34KER_BRIDGE_PROTOCOL_VERSION 1U
#define FBR34KER_PHYSICAL_SESSION_SCHEMA_VERSION 1U
#define FBR34KER_PHYSICAL_VALIDATION_SCHEMA_VERSION 1U
